//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMPR.Client.Resources
{
	using System;


	/// <summary>
	///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
	/// </summary>
	// Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
	// -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
	// Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
	// mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class ApplicationTranslations
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal ApplicationTranslations()
		{
		}

		/// <summary>
		///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMPR.Client.Resources.ApplicationTranslations", typeof(ApplicationTranslations).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
		///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture
		{
			get
			{
				return resourceCulture;
			}
			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Neue Ordnerabfrage ähnelt.
		/// </summary>
		public static string ButtonNewQuery
		{
			get
			{
				return ResourceManager.GetString("ButtonNewQuery", resourceCulture);
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Neue Abfrage ähnelt.
		/// </summary>
		public static string DialogNewQuery
		{
			get
			{
				return ResourceManager.GetString("DialogNewQuery", resourceCulture);
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Abfrage: {0} ähnelt.
		/// </summary>
		public static string TextEvaluation
		{
			get
			{
				return ResourceManager.GetString("TextEvaluation", resourceCulture);
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die In Explorer öffnen ähnelt.
		/// </summary>
		public static string TreeOpenInExplorer
		{
			get
			{
				return ResourceManager.GetString("TreeOpenInExplorer", resourceCulture);
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Rekursiv zusammenklappen ähnelt.
		/// </summary>
		public static string TreeRecursiveCollapse
		{
			get
			{
				return ResourceManager.GetString("TreeRecursiveCollapse", resourceCulture);
			}
		}

		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Rekursiv aufklappen ähnelt.
		/// </summary>
		public static string TreeRecursiveExpand
		{
			get
			{
				return ResourceManager.GetString("TreeRecursiveExpand", resourceCulture);
			}
		}
	}
}
